from app.crud.neurosploit.scan import (
    get_scan,
    get_scans,
    get_scans_by_user,
    create_scan,
    update_scan,
    delete_scan,
    update_scan_progress,
    update_scan_stats,
    get_scan_with_stats,
)

from app.crud.neurosploit.target import (
    get_target,
    get_targets,
    get_targets_by_scan,
    create_target,
    update_target,
    delete_target,
)

from app.crud.neurosploit.endpoint import (
    get_endpoint,
    get_endpoints,
    get_endpoints_by_scan,
    create_endpoint,
    update_endpoint,
    delete_endpoint,
)

from app.crud.neurosploit.vulnerability import (
    get_vulnerability,
    get_vulnerabilities,
    get_vulnerabilities_by_scan,
    create_vulnerability,
    update_vulnerability,
    delete_vulnerability,
    get_vulnerability_test,
    get_vulnerability_tests,
    get_vulnerability_tests_by_scan,
    create_vulnerability_test,
    update_vulnerability_test,
    delete_vulnerability_test,
)

from app.crud.neurosploit.report import (
    get_report,
    get_reports,
    get_reports_by_scan,
    create_report,
    update_report,
    delete_report,
)

from app.crud.neurosploit.prompt import (
    get_prompt,
    get_prompts,
    create_prompt,
    update_prompt,
    delete_prompt,
)

from app.crud.neurosploit.agent_task import (
    get_agent_task,
    get_agent_tasks,
    get_agent_tasks_by_scan,
    create_agent_task,
    update_agent_task,
    delete_agent_task,
)

from app.crud.neurosploit.vuln_lab import (
    get_vuln_lab_challenge,
    get_vuln_lab_challenges,
    create_vuln_lab_challenge,
    update_vuln_lab_challenge,
    delete_vuln_lab_challenge,
)

__all__ = [
    "get_scan",
    "get_scans",
    "get_scans_by_user",
    "create_scan",
    "update_scan",
    "delete_scan",
    "update_scan_progress",
    "update_scan_stats",
    "get_scan_with_stats",
    "get_target",
    "get_targets",
    "get_targets_by_scan",
    "create_target",
    "update_target",
    "delete_target",
    "get_endpoint",
    "get_endpoints",
    "get_endpoints_by_scan",
    "create_endpoint",
    "update_endpoint",
    "delete_endpoint",
    "get_vulnerability",
    "get_vulnerabilities",
    "get_vulnerabilities_by_scan",
    "create_vulnerability",
    "update_vulnerability",
    "delete_vulnerability",
    "get_vulnerability_test",
    "get_vulnerability_tests",
    "get_vulnerability_tests_by_scan",
    "create_vulnerability_test",
    "update_vulnerability_test",
    "delete_vulnerability_test",
    "get_report",
    "get_reports",
    "get_reports_by_scan",
    "create_report",
    "update_report",
    "delete_report",
    "get_prompt",
    "get_prompts",
    "create_prompt",
    "update_prompt",
    "delete_prompt",
    "get_agent_task",
    "get_agent_tasks",
    "get_agent_tasks_by_scan",
    "create_agent_task",
    "update_agent_task",
    "delete_agent_task",
    "get_vuln_lab_challenge",
    "get_vuln_lab_challenges",
    "create_vuln_lab_challenge",
    "update_vuln_lab_challenge",
    "delete_vuln_lab_challenge",
]
